# Generated by Django 4.2.4 on 2025-12-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
